---
eureka:
  client:
    serviceUrl: 
      defaultZone: http://eureka-primary:8011/eureka,http://eureka-secondary:8012/eureka,http://eureka-tertiary:8013/eureka

---
words: NotAplicable
spring:
  profiles: sentence
  application:
    name: client-solution
server:
  port: 8020

---
words: I,You,He,She,It
spring:
  profiles: subject
  application:
    name: client-solution
server:
  port: 8002

---
words: a,the
spring:
  profiles: article
  application:
    name: client-solution
server:
  port: 8003

---
words: ran,knew,had,saw,bought
spring:
  profiles: verb
  application:
    name: client-solution
server:
  port: 8004

---
words: reasonable,leaky,suspicious,ordinary,unlikely
spring:
  profiles: adjective
  application:
    name: client-solution
server:
  port: 8006

---
words: boat,book,vote,seat,backpack,partition,groundhog
spring:
  profiles: noun
  application:
    name: client-solution
server:
  port: 8005
 
