---
eureka:
  client:
    serviceUrl: 
      defaultZone: http://eureka-primary:8011/eureka,http://eureka-secondary:8012/eureka,http://eureka-tertiary:8013/eureka

---
spring:
  profiles: sentence
  application:
    name: client-solution
server:
  port: 8020

---
spring:
  profiles: article
  application:
    name: client-solution
server:
  port: ${PORT:${SERVER_PORT:0}}
