---
spring:
  profiles:
    active: default
limits-service:
  minimum: 8
  maximum: 888
---
spring:
  profiles:
    active: dev
limits-service:
  minimum: 1
  maximum: 111
---
spring:
  profiles:
    active: qa
limits-service:
  minimum: 2
  maximum: 222  